controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

api_fruits_index:
    path: /fruits
    methods: [GET]
    controller: App\Controller\ItemController.fruit

api_vegetables_index:
    path: /vegetables
    methods: [GET]
    controller: App\Controller\ItemController.vegetable
